### ISSUE TITLE
Why are we passing cloned objects to callbacks?

### ISSUE THREAD

**Issue by kripper** [PHP-on-Couch/PHP-on-Couch#102]
Why are we passing cloned objects to the callback in `src\Adapter\CouchHttpAdapterSocket.php`?

```
$clone = $caller ? clone $caller : null;
...
$break = call_user_func($callable, json_decode($line), $clone);
```

**Comment by popojargo** [comment]
That's a very good question. I tried digging in with git blame but it's not obvious why it was added. I'm not really spending any efforts on this library at the moment and I don't think it's worth changing given the possible consequences it could have.
