### ISSUE TITLE
Can't get Cookie authentification

### ISSUE THREAD

**Issue by kl3sk** [PHP-on-Couch/PHP-on-Couch#21]
I want to use cookie authentification, but from __construct in CouchClient, it nevers return sessioncookie

I fix the problem with double quotted "\r\n" 

``` CouchClient.php
L132:            list($headers, $body) = explode("\r\n\r\n", $rawData, 2);
L133:            $headersArray = explode("\r\n", $headers);

```
https://github.com/PHP-on-Couch/PHP-on-Couch/blob/master/src/CouchClient.php#L132

Additional quesiton:
How can i get this cookie, in the old repo, getSessionCookie() exists but not now

Thx

**Comment by popojargo** [comment]
@kl3sk I probably forgot to merge it in one of the PR. I will readd getSessionCookie()

**Comment by popojargo** [comment]
I added the getter for sessionCookie. I also added test for the CouchClient Constructor and cookie_auth.
