### ISSUE TITLE
Missing phpDoc @method Tags in CouchClient class

### ISSUE THREAD

**Issue by ternary-Operator** [PHP-on-Couch/PHP-on-Couch#34]
Just a slight improvement:
Please add "method" phpDoc parts for all methods available through CouchClient->queryDefs, so the IDE recognizes them. 

```
$client->limit(100)
  ->descending(true)
```

```
/**
 * CouchDB client class
 * 
 * This class implements all required methods to use with a CouchDB server
 *
 * @method CouchClient descending($descending)
 */
class CouchClient extends Couch
{
```
https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html

**Comment by popojargo** [comment]
Changes coming with #36
