### ISSUE TITLE
Class 'PHPOnCouch\CouchException' not found

### ISSUE THREAD

**Issue by bgold0** [PHP-on-Couch/PHP-on-Couch#35]
I get the following error when I try to do replication. I think I did everything the documentation told me to do and even tried `use PHPOnCouch\ CouchException;` as well. 

Do you know what I am doing wrong?

> Fatal error: Class 'PHPOnCouch\CouchException' not found in /../vendor/popojargo/php-on-couch/src/CouchReplicator.php on line 164

	use PHPOnCouch\Couch;
    use PHPOnCouch\CouchAdmin;
    use PHPOnCouch\CouchClient;
    use PHPOnCouch\CouchDocument;
    use PHPOnCouch\CouchReplicator;

    $client = new CouchClient ("http://localhost:8080", "u12345");
	$replicator = new CouchReplicator($client);
	$response = $replicator->from("http://localhost:8000/u12345;

**Comment by popojargo** [comment]
` /../vendor/popojargo/php-on-couch/src/CouchReplicator.php` : You are using the version from my fork. Please update your composer file to use php-on-couch release.

**Comment by bgold0** [comment]
I'm using the following composer file, is this not right?

    "PHP-on-Couch/php-on-couch": "dev-master",

**Comment by popojargo** [comment]
Do you have /vendor/php-on-couch/php-on-couch/src/CouchReplicator.php ?
I'm on gitter if you want faster support.
