### ISSUE TITLE
isValidDatabaseName blocks system tables except for "_users"

### ISSUE THREAD

**Issue by AbhinavBajpai** [PHP-on-Couch/PHP-on-Couch#43]
I'm trying to access the "_replicator" table, but the validation check in CouchClient.php (line 288) prevents this.

Would there be any catastrophic repercussions if I added an exception for "_replicators"  in the initial if statement?  If not I'd be happy to fork and make a pull request.

**Comment by popojargo** [comment]
This have been discussed in order  issues but I think it would be good to simply remove this restrictions. 

You can fork and create a pull request.

- [ ] Allow database names starting with an underscore
- [ ] Update the unit tests
- [ ] Update the documentation if necessary

**Comment by popojargo** [comment]
@AbhinavBajpai  Are you still available to do fix this issue?

**Comment by AbhinavBajpai** [comment]
Hi, sorry about the delay.  Just submitted a PR.

**Comment by popojargo** [comment]
Closed with #45 

Thank you for your contribution.
