### ISSUE TITLE
How to create .env file using composer.

### ISSUE THREAD

**Issue by mrbobbybryant** [PHP-on-Couch/PHP-on-Couch#51]
I am trying to use this library in production but It is not clear how to create the .env file dynamically after running composer.

I noticed your library is using `PHP dotenv` which says:

> phpdotenv is made for development environments, and generally should not be used in production. In production, the actual environment variables should be set so that there is no overhead of loading the .env file on each request. This can be achieved via an automated deployment process with tools like Vagrant, chef, or Puppet, or can be set manually with cloud hosts like Pagodabox and Heroku.

Any ideas? I am using Deploybot and I'm not sure manually creating a file like this is an option for me.

Maybe you should allow users the ability to define where the .env file will be located? ( Currently it is set to `__dir__` ). That way other developers could create the file within the root of their project.

Thoughts?

**Comment by popojargo** [comment]
Dotenv allow you to parse the environment variables from a file. As they recommend, you should explicitly define your environment variables  instead of using files in production.

For example, in Heroku you can define some env variables when your application is running.

**Comment by mrbobbybryant** [comment]
Thanks. I was able to use composer to create the .env file during the deployment of my code.
