### ISSUE TITLE
user-agent addition

### ISSUE THREAD

**Issue by asarubbo** [PHP-on-Couch/PHP-on-Couch#52]
Hi,
this library sets the user-agent to blank, so the webserver sees a request like:
```
$IP - $USER [23/Apr/2018:14:47:27 +0200] "GET /location_10724 HTTP/1.1" 403 334 "-" "-" "-"
```

Can you add a way to configure the user-agent and/or set one by default?
Thanks

**Comment by popojargo** [comment]
You should be able to set any CURL configuration with a environment variables or a .env file. 
You could set [CURLOPT_USERAGENT](https://davidwalsh.name/set-user-agent-php-curl-spoof) in the configuration file.

For more info about configuration: http://php-on-couch.readthedocs.io/en/latest/quickstart/configuration.html

**Comment by asarubbo** [comment]
Ok, it worked, thanks.
