### ISSUE TITLE
PHPDoc is not clear in some places

### ISSUE THREAD

**Issue by sinri** [PHP-on-Couch/PHP-on-Couch#58]
For example, in 2.0.5, Class `CouchClient`, 

For function `getDoc`, current PHPDoc is `@return object|array CouchDB document`. Actually it should be `@return CouchDocument CouchDB document`, I think.

And the same method throws CouchException but not shown.

PHPDoc is quite helpful when developing with PHPStorm or so. Refine them might be good.

**Comment by popojargo** [comment]
The getDoc can return an array if you specific the [asArray()](https://php-on-couch.readthedocs.io/en/latest/api/couchclient/document.html#asarray) chaining method. You can always submit a PR to improve the doc or point me specific ambiguities

**Comment by popojargo** [comment]
Reopen if you have more specification.
