### ISSUE TITLE
Lucene querying capabilitites

### ISSUE THREAD

**Issue by andreyvk** [PHP-on-Couch/PHP-on-Couch#68]
Hi there,

CouchDB is often used with Lucene over couchdb-lucene driver. Are there any plans to add lucene support into this driver?

**Comment by popojargo** [comment]
Hi @andreyvk ! I don't have a lot time and I've never used Lucene with CouchDB so setting up my environment to implement and test it would require me even more time.

Perhaps with this [docker image](https://github.com/klaemo/docker-couchdb-lucene) it could be easier to play around with it.

You can always use this [function](https://github.com/PHP-on-Couch/PHP-on-Couch/blob/master/src/CouchClient.php#L218) to call the lucene endpoint.

Related to that, I could document the exposed function for custom API calls.

**Comment by andreyvk** [comment]
@popojargo thanks! I could probably extend `CouchClient` class to add lucene functionality. However, could you plz explain what does `CouchClient::__call()` do? Seems like it's some kind of validation. A call to lucene has an extended set of query parameters: besides standard `skip`, `limit`, `include_docs` there are others like `include_fields`, which tells Lucene to include fields that are stored together with indexes (in case if i dont want to pull the whole doc and just get a few attributes together with the search result). Will that be a problem during a call to `CouchClient::queryAndValid()` ?

**Comment by popojargo** [comment]
In php __call() is executed when you call an object property/class when it's not explicitly defined (I think).

So when you do `$client->limit(1)`, the `__call()` function is called. We use this magic property to easily map query parameters. 

Query parameters are defined here: https://github.com/PHP-on-Couch/PHP-on-Couch/blob/master/src/CouchClient.php#L85

## QueryDefs
It's a hashmap of query parameters. The key is the name of the parameter.

Example for $queryDef['skip']:

`$client->skip(1)`

The value of the hasmap define that it takes as a parameter. Its defined as: [name=>"",filter->""]

The name is the name of the query parameter for Couch. The filter is a string that identify the type of the parameters. 

## QueryAndValid

This function is the general function to call CouchDB. It takes a url path (relative to your server), the parameters to send and the expected http status codes. 

When you call queryAndValid, the $queryDefs parameters will be applied to the query and resetted.

**Comment by andreyvk** [comment]
hi @popojargo ,

Got it. It seems as long as I dont use chained methods to set query parameters, it should work fine then.

Thanks a lot!
