### ISSUE TITLE
Upgrade `vlucas/phpdotenv`

### ISSUE THREAD

**Issue by jsgv** [PHP-on-Couch/PHP-on-Couch#71]
Any thoughts on upgrading `vlucas/phpdotenv` to version ^3?

I am unable to install in a Laravel 5.8 project due to different dependency versions.

**Comment by popojargo** [comment]
Can you check if there are not any breaking change? If so, you could submit a pr

**Comment by jsgv** [comment]
I found an alternate package that works for me. Thanks for the reply.
