### ISSUE TITLE
Connection options ignored in 'deleteDatabase' function

### ISSUE THREAD

**Issue by dzero1** [PHP-on-Couch/PHP-on-Couch#75]
I tried to delete a database with deleteDatabase(). But I found it'll ignored the connection options.

Not working code :

`
$couch_dns = "https://couchdb.databaseserver.com";
$couch_options = [  "username" => "admin", "password" => "password"  ]

$tmp_client = new CouchClient($couch_dns, $db, $couch_options);
$result = $tmp_client->deleteDatabase();
echo json_encode($result)."\n";
`

this will return {"error":"unauthorized","reason":"You are not a server admin."}

but if i change url as following;
$couch_dns = "https://**admin:password@**couchdb.databaseserver.com";

the deletion was happened. 

So I guess the options was ignored when calling that function.

**Comment by popojargo** [comment]
@dzero1 Do you have the same error with the latest version^
