### ISSUE TITLE
`autoload.php` throws warning for latest composer snapshot

### ISSUE THREAD

**Issue by SunMar** [PHP-on-Couch/PHP-on-Couch#76]
Hi,

When using the latest composer snapshot and having it generate optimised autoload files, the following deprecation warning is shown:

```
Deprecation Notice: Class PHPOnCouch\Autoload located in ./vendor/php-on-couch/php-on-couch/src/autoload.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v1.11+.
```

However I'm not sure if `autoload.php` is still needed at all, instead of renaming the file or class, maybe it can be removed altogether? But it seems like some of the tests are also including them. It's a bit confusing to me. I don't mind creating a PR to fix this warning, but I'll need some guidance as to what direction to go to with this fix (rename or delete the file) and how I can run the test suite to verify my changes.

**Comment by popojargo** [comment]
The test setup has been weirdly setup by myself and would require some cleanup. The custom autoload file was only created as an example and is used by the tests only. 

Therefore, I can't really remove it since people might be using it and it could be a breaking change.

**Comment by popojargo** [comment]
So what I suggest:

1. Duplicate the file and rename it for Autoload.php so  it can be loaded by the composer autoloader.
2. Add a deprecation notice in the older autoload.php
3. Remove the the older file on the next major release

**Comment by popojargo** [comment]
Should be fixed with the new release
