### ISSUE TITLE
vlucas/phpdotenv conflicts with Laravel >= 5.8

### ISSUE THREAD

**Issue by SunMar** [PHP-on-Couch/PHP-on-Couch#78]
Hi,

I just tried to upgrade to 3.0 but since in my `composer.json` I still had `^2.0` I found out that I actually was still stuck on `2.0.3`. In `2.0.4` the use of `vlucas/phpdotenv` was introduced, but Laravel 5.8 and 6.x depend on `^3.3`, making PHP-on-Couch >= 2.0.4 incompatible with Laravel >= 5.8. From looking at https://github.com/vlucas/phpdotenv/releases/tag/v3.0.0 it seems like the breaking changes are very minor and that it should be fairly easy to upgrade as well to `^3.3`, so that the newest 3.0 can also be used with the newest version of Laravel.

**Comment by popojargo** [comment]
@SunMar Wanna give it a try?

**Comment by SunMar** [comment]
@popojargo Sure, I can take a stab at it. In the mean time I found https://php-on-couch.readthedocs.io/en/latest/quickstart/testing.html which I hope will help me run the tests :).

Also I saw (https://php-on-couch.readthedocs.io/en/latest/quickstart/codestyle.html) that the coding style is still based on PSR-1, which is pretty old now. Maybe something an idea to move to PSR-12, but that would be its own ticket I guess.

**Comment by popojargo** [comment]
@SunMar I'm not actively working on this library anymore so I'm offering limited support to make it work. The testing instructions might help you but feel free to tweak it to make it more usable!

As for the codestyle, this can also be updated but I'm not willing to spend time for that

**Comment by popojargo** [comment]
Also, I don't think there are any tests for the configuration. So feel free to ping me if you have any questions

**Comment by SunMar** [comment]
Np, I have been busy but I will take a look next week.

**Comment by SunMar** [comment]
@popojargo Was a little bit busier than I had hoped, but finally managed to create a PR. It was a very minor change so I also didn't touch any code styling or stuff like that :).

**Comment by SunMar** [comment]
@popojargo do you know when you'll tag this in a new release? then I can finally upgrade away from 2.0.3 :)

**Comment by popojargo** [comment]
Upadting the tag atm
