### ISSUE TITLE
v1.x VS v2.0

### ISSUE THREAD

**Issue by ClemensSahs** [PHP-on-Couch/PHP-on-Couch#8]
he I want start a discussion what thinks we need and want we can implement before we make a BC break

without BC break:
- automatic tests (travis ci)
- code coverage (coveralls)
- autoloading over composer
- phpunit upgrade

need BC break:
- namespaces (psr0)
- psr1 (basic coding standard)

possible for both:
- better adapter logic (curl / socket)
- psr2 (code style standard)

please write me your ideas I will update the wanted list

regards

**Comment by popojargo** [comment]
This repo seems a bit unactive as the original repo. Michael gave me the collaborator rights on his repo but I still don't the required rights to setup webhooks for travis, coveralls, etc.  By joining this team, will I be able to setup web-hooks?

**Comment by popojargo** [comment]
@PHP-on-Couch/owners I will merge changes from https://github.com/dready92/PHP-on-Couch. 
@ClemensSahs  are you still active on this project or I am free to do what I think is the best for this library?

I could also add a mention to the original repository to point to this repository so people are more up to date.
