### ISSUE TITLE
CouchClient creation error with cookie_auth option and username containing "@"

### ISSUE THREAD

**Issue by antonioturdo** [PHP-on-Couch/PHP-on-Couch#81]
Trying to create a CouchClient with cookie_auth option and an username containing "@" I get an error in the POST to /_session because username is modified by parse_url and urlencode functions.

I think that when the cookie_auth option is passed there is no reason to add username and password in the dsn and then remove them.

**Comment by popojargo** [comment]
Should be fixed by #87
