### ISSUE TITLE
Latest release using incorrect commit

### ISSUE THREAD

**Issue by tvStatic** [PHP-on-Couch/PHP-on-Couch#88]
The 3.0.1 release, titled "Support CouchDB 3.0" does not appear to match the commit that adds the support. The latest commit with description "Update library for CouchDB 3.x (#87)" is `8bc21bf`. The commit for the 3.0.1 tag is `0961c79` which is the commit prior and has the description "Update vlucas/phpdotenv to ^3.3 (#79)".

**Comment by popojargo** [comment]
My bad, I'll retag the release tonight

**Comment by popojargo** [comment]
@tvStatic  Should be better now!
