### ISSUE TITLE
Key 0 of a document is removed on record()

### ISSUE THREAD

**Issue by fluffis** [PHP-on-Couch/PHP-on-Couch#90]
The following code is a working example to demonstrate the issue:
```PHP
$a = [
    0 => [
        'a' => 'b',
        'foo' => 'bar'
    ],
    1 => [
        'c' => 'd',
        'bar' => 'foo'
    ]
];

$cclient = new \PHPOnCouch\CouchClient("http://user:password@127.0.0.1:5984/", "test");
$doc = new \PHPOnCouch\CouchDocument($cclient);
$doc->set($a);
echo $doc->id() . "\n";
print_r($doc->getFields());
```

The generated output is:
``` 
bb9f9a242b7537c4afee108ca6100048
stdClass Object
(
    [1] => Array
        (
            [c] => d
            [bar] => foo
        )

    [_id] => bb9f9a242b7537c4afee108ca6100048
    [_rev] => 1-2f23eb3c355727f519326cf8371faf77
)
```

The problem is that `$a[0]` is missing in the stored document. 

I've identified the problem to be the use if `in_array()` in [CouchClient.php:707](https://github.com/PHP-on-Couch/PHP-on-Couch/blob/master/src/CouchClient.php#L707)

According to the PHP docs, it's a known behavior that `in_array(0, ['any', 'array']);` will return TRUE. A solution may be to turn on strict checking for this function:
```PHP
if (in_array($key, CouchClient::$underscoredPropertiesToRemoveOnStorage, true)) {
}
```

**Comment by popojargo** [comment]
Seems like it would do it. Want to create a PR + a simple unit test that covers that?
