### ISSUE TITLE
phpdotenv clash

### ISSUE THREAD

**Issue by flarpy** [PHP-on-Couch/PHP-on-Couch#92]
This is fyi, on a fresh install of laravel 8+ there is a version conflict with phpdotenv:

` composer require php-on-couch/php-on-couch
Using version ^3.0 for php-on-couch/php-on-couch
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install php-on-couch/php-on-couch 3.0.2
    - Conclusion: don't install php-on-couch/php-on-couch 3.0.1
    - Conclusion: remove vlucas/phpdotenv v5.2.0
    - Installation request for php-on-couch/php-on-couch ^3.0 -> satisfiable by                                                                              php-on-couch/php-on-couch[3.0.0, 3.0.1, 3.0.2].
    - Conclusion: don't install vlucas/phpdotenv v5.2.0
    - php-on-couch/php-on-couch 3.0.0 requires vlucas/phpdotenv ^3.3 -> satisfia                                                                             ble by vlucas/phpdotenv[3.3.x-dev, 3.4.x-dev, 3.5.x-dev, 3.6.x-dev, v3.3.0, v3.3                                                                             .1, v3.3.2, v3.3.3, v3.4.0, v3.5.0, v3.6.0, v3.6.1, v3.6.2, v3.6.3, v3.6.4, v3.6                                                                             .5, v3.6.6, v3.6.7].
    - Can only install one of: vlucas/phpdotenv[3.3.x-dev, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[3.4.x-dev, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[3.5.x-dev, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[3.6.x-dev, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.3.0, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.3.1, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.3.2, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.3.3, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.4.0, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.5.0, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.0, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.1, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.2, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.3, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.4, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.5, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.6, v5.2.0].
    - Can only install one of: vlucas/phpdotenv[v3.6.7, v5.2.0].
    - Installation request for vlucas/phpdotenv (locked at v5.2.0) -> satisfiabl                                                                             e by vlucas/phpdotenv[v5.2.0].`

**Comment by popojargo** [comment]
I'll probably just get ride of phpdotenv. I'll just create a new major release at this point since it's breaking

**Comment by popojargo** [comment]
Removed, I'll create a new version soon

**Comment by thelfensdrfer** [comment]
Hey, can you reopen this issue until a new version is released?

**Comment by popojargo** [comment]
I think it's merged on the main branch so it should be available on the unstable branch. Let me try to make a release this week

**Comment by popojargo** [comment]
Create 4.0.0
