### ISSUE TITLE
A default limit of 25 is applied to ->find()

### ISSUE THREAD

**Issue by pimhakkert** [PHP-on-Couch/PHP-on-Couch#98]
I can't get more than 25 documents unless I explicitly tell the CouchClient to fetch more results. 

This doesn't seem to be documented anywhere, and leads people to wonder why their code is broken. Why is it set to be like this? Why is the default not to fetch ALL documents?

`$data = $this->db->find($dataSelector);` results in 25 documents.
`$data = $this->db->limit(999999)->find($dataSelector);` results in the correct amount of documents.

**Comment by popojargo** [comment]
This CouchDB client is just a tiny wrapper onto the actual API. We let CouchDB define the default values and by default, CouchDB as a default limit of 25 documents: https://docs.couchdb.org/en/stable/api/database/find.html?highlight=find

Sorry for the inconvenience
